# Generated by Django 3.0.6 on 2020-05-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CubbyRequest',
        ),
    ]
