# Generated by Django 3.2.7 on 2021-09-20 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialized_subscription_at', models.DateTimeField()),
                ('chose_collection_method_at', models.DateTimeField()),
                ('entered_payment_method_at', models.DateTimeField()),
                ('completed_subscription_at', models.DateTimeField()),
                ('prefers_autopay', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
