language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install

env:
  - ENVIRONMENT=test
  - DATABASE_URL=postgres://postgres@localhost:5432/django-clubhouse-test
  - SERVER_HOSTNAME=localhost
  - SERVER_PORT=8000
  - SERVER_PROTOCOL=https

script:
  - pipenv run ./manage.py test
