# Generated by Django 2.2.6 on 2019-11-11 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_coupon_identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(help_text='Who qualifies for this discount, and what are its terms?')),
                ('allow_family_memberships', models.BooleanField(default=False, verbose_name='Allow family memberships?')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=100, verbose_name='Given Name')),
                ('family_name', models.CharField(max_length=100, verbose_name='Family Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('member_since', models.DateField(verbose_name='Date Joined')),
                ('address_street1', models.CharField(max_length=100, verbose_name='Street Address')),
                ('address_street2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address 2')),
                ('address_city', models.CharField(max_length=100, verbose_name='City')),
                ('address_state', localflavor.us.models.USStateField(max_length=2, verbose_name='State')),
                ('address_zip', localflavor.us.models.USZipCodeField(max_length=10, verbose_name='Zip Code')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_can_receive_sms', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_plan_identifier', models.CharField(help_text="Don't change this.", max_length=100)),
                ('name', models.CharField(help_text='This text will appear in member-facing forms, so pick clear and descriptive.', max_length=30)),
                ('requires_setup_fee', models.BooleanField(default=True)),
                ('sort_priority', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('incomplete_expired', 'Incomplete (Expired)'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], max_length=30)),
                ('membership_type', models.CharField(choices=[('household', 'Household'), ('student_team', 'Student Team')], max_length=50)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal'), ('offline', 'Cold, Hard Cash'), ('ach', 'Direct Deposit')], max_length=50)),
                ('valid_through', models.DateField()),
                ('team_name', models.CharField(blank=True, help_text='This value is ignored on Household memberships', max_length=40)),
                ('team_organization', models.CharField(blank=True, help_text='The school or organization to which team members belong', max_length=40)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Discount')),
                ('membership_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_memberships', to='membership.Member')),
                ('payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.PaymentPlan')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Membership'),
        ),
    ]
