# Generated by Django 3.2.2 on 2021-05-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_label',
            field=models.CharField(default='hour', max_length=20),
        ),
    ]
