# Generated by Django 3.2.2 on 2021-05-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0003_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
