# Generated by Django 2.2.6 on 2019-11-11 22:11

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import signup.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='SignupProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('contact_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('liability_waiver_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('membership_activation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('application_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('payment_plan_collected_at', models.DateTimeField(blank=True, null=True)),
                ('payment_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_screen_passed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Member')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Membership')),
            ],
            options={
                'verbose_name_plural': 'signup progress records',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('contact_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('liability_waiver_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('membership_activation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('application_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('given_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('family_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=signup.models.two_weeks_from_now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Member')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Membership')),
                ('signup_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.SignupProgress')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
