# Generated by Django 3.0.6 on 2020-06-04 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import signup.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('family_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('civicrm_identifier', models.CharField(max_length=6, verbose_name='CiviCRM Contact ID')),
                ('basic_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('contact_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('liability_waiver_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('membership_activation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('application_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('payment_plan_collected_at', models.DateTimeField(blank=True, null=True)),
                ('payment_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('paid_setup_fee_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_screen_passed_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_identifier', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Stripe Customer ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'signup progress records',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('family_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('civicrm_identifier', models.CharField(max_length=6, verbose_name='CiviCRM Contact ID')),
                ('basic_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('contact_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('liability_waiver_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('membership_activation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('application_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=signup.models.two_weeks_from_now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('plus_one_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.Registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
