# Generated by Django 3.0.7 on 2020-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20200605_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='application_rejected_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='membership_activation_completed_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='application_rejected_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='membership_activation_completed_at',
        ),
        migrations.AddField(
            model_name='invitation',
            name='account_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='account_invitation_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='account_invitation_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='application_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='keyfob_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='membership_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='account_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='account_invitation_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='account_invitation_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='application_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='keyfob_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='membership_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
