# Generated by Django 3.0.7 on 2020-06-09 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20200608_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True),
        ),
    ]
