# Generated by Django 3.0.7 on 2020-06-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20200609_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
