# Generated by Django 3.2.4 on 2021-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_delete_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='civicrm_identifier',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='CiviCRM Contact ID'),
        ),
    ]
