# Generated by Django 3.2.4 on 2021-06-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_alter_registration_civicrm_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='membership_household_record',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='membership_person_record',
            field=models.URLField(blank=True, null=True),
        ),
    ]
