# Generated by Django 3.0.6 on 2020-05-30 09:12

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_civicrm_keyfob_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.ClubhouseUserManager()),
            ],
        ),
    ]
