# Generated by Django 3.2.4 on 2021-06-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_stripe_customer_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='member_identifier',
        ),
        migrations.AddField(
            model_name='user',
            name='membership_person_record',
            field=models.URLField(blank=True, null=True),
        ),
    ]
