# Generated by Django 3.0.6 on 2020-05-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_exempt_from_member_timeslot_quota',
            field=models.BooleanField(default=False, verbose_name="Reservations in this area do not count against a member's daily quota."),
        ),
    ]
