# Generated by Django 3.2.2 on 2021-05-17 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0002_area_is_exempt_from_member_timeslot_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department Name')),
                ('slug', models.SlugField(verbose_name='URL Slug')),
                ('shop_contact_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('stripe_donation_product_identifier', models.CharField(max_length=50, verbose_name='Stripe product identifier for donations')),
                ('area_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_area_manager', to=settings.AUTH_USER_MODEL)),
                ('secondary_area_managers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
