# Generated by Django 3.2.2 on 2021-05-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_department_training_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='department',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
