# Generated by Django 3.2.2 on 2021-05-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20210525_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='map',
            field=models.FileField(blank=True, help_text='This should be an SVG file with an approximate 4:3 aspect ratio.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='photo',
            field=models.ImageField(blank=True, help_text='Any image file with a 4:3 aspect ratio will work.', null=True, upload_to=''),
        ),
    ]
