# Generated by Django 3.2.7 on 2021-09-20 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0006_auto_20210525_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='secondary_area_managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
