# Generated by Django 2.2.6 on 2019-12-09 08:36

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('contact_info_collected_at', models.DateTimeField(blank=True, null=True)),
                ('liability_waiver_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('membership_activation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('application_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('member_identifier', models.UUIDField(blank=True, null=True)),
                ('household_identifier', models.UUIDField(blank=True, null=True)),
                ('dashboard_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
